[package]
name = "tokenizers-cpp"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]

tokenizers = { version = "0.13.3", default-features = false, features = ["onig"] }
