# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit
default_install_hook_types:
  - pre-commit
repos:
  # ---------- General file checks ----------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
        exclude: ^3rdparty/
      - id: mixed-line-ending
        exclude: ^3rdparty/
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^3rdparty/
      - id: check-yaml
      - id: check-toml

  # ---------- YAML lint ----------
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-file
          - .yamllint.yaml
        exclude: ^\.github/

  # ---------- TOML format ----------
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format

  # ---------- Python: ruff ----------
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  # ---------- C/C++: clang-format ----------
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v20.1.8"
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda, objective-c++]
        exclude: |
          (?x)^(.*cubin\.cpp$|.*fmha_cubin\.h|3rdparty/.*)$
