version: '3.8'

services:
  # Development environment (interactive shell, source mounted)
  mlc-dev:
    build:
      context: .
      target: development
    image: mlc-llm:dev
    container_name: mlc-dev
    volumes:
      - .:/workspace
      - mlc-cache:/root/.cache
    working_dir: /workspace
    stdin_open: true
    tty: true
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONPATH=/workspace/python:/workspace/3rdparty/tvm/python
    command: /bin/bash

  # Production runtime (non-interactive)
  mlc-prod:
    build:
      context: .
      target: production
    image: mlc-llm:prod
    container_name: mlc-prod
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: --help

  # CI testing
  mlc-test:
    build:
      context: .
      target: ci
    image: mlc-llm:ci
    container_name: mlc-test
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: python -m pytest tests/ -v

volumes:
  mlc-cache:
    driver: local