name: mlc-dev
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - cmake>=3.24
  - git
  - git-lfs
  - rust
  - libgcc-ng
  - zstd
  - jupyter
  - tensorboard
  - pytest
  - pytest-cov
  - pytest-xdist
  - black
  - isort
  - pylint
  - mypy
  - pre-commit
  - cuda-toolkit=12.2
  - pip
  - pip:
    - fastapi
    - uvicorn[standard]
    - openai
    - jsonschema
    - requests
    - numpy
    - torch
    - torchvision
    - torchaudio
    - transformers
    - huggingface-hub
    - accelerate
    - datasets
    - wandb
    - mlflow
