blank_issues_enabled: false

contact_links:
  - name: Check the MLC-LLM Documentation
    url: https://llm.mlc.ai/docs/
    about: Our documentation might provide answers to your questions.
  - name: Chat on Discord
    url: https://discord.gg/9Xpy2HGBuD
    about: Join the Discord Server to live chat with the community.
