NUM_CACHE_EVICTONS = "num_cache_evictions"
E2E_LATENCY = "e2e_latency"
FIRST_TOKEN_LATENCY = "first_token_latency"
KV_CACHE_UTILIZATION = "kv_cache_utilization"
BATCHED_PREFILL_TOKENS = "batched_prefill_tokens"
BATCHED_DECODE_TOKENS = "batched_decode_tokens"
